spring.application.name=ims

spring.datasource.url=jdbc:mysql://localhost:3306/orque_ims?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=false

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# ROOT should NOT be DEBUG
logging.level.root=INFO

# Your project only (optional debug)
logging.level.com.orque=DEBUG